<?php
/**
 * Custom hooks
 *
 * @package UnderStrapClue
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

//--------------------------------------------------------
// Custom WP admin menu order, adjust the list as needed
//--------------------------------------------------------
function cd_custom_menu_order($menu_ord) {
	if (!$menu_ord) return true;

	return array(
		'index.php',							// Dashboard
		'edit.php?post_type=page',				// Pages
		'edit.php',								// Posts
		'edit.php?post_type=case-study',		// Case Study
		'upload.php',							// Media
		'separator1', // First separator
		'plugins.php',							// Plugins
		'edit.php?post_type=acf-field-group',	// ACF
		'gf_edit_forms',						// Gravity Forms
		'wpseo_dashboard',						// Yoast SEO
		'wpml_plugin_log',						// WP Mail Logging
		'separator2', // Second separator
		'users.php',							// Users
		'theme-config',							// Theme Config
		'edit-comments.php',					// Comments
		'themes.php',							// Appearance
		'tools.php',							// Tools
		'options-general.php',					// Settings
	);
}

function cd_set_custom_menu_order() {
	add_filter('custom_menu_order', '__return_true');
	add_filter('menu_order', 'cd_custom_menu_order');
}
add_action('admin_menu', 'cd_set_custom_menu_order');

// Rearrange Theme Settings - Option Pages
add_action('admin_menu', function() {
	// Remove existing submenus
	remove_submenu_page('theme-config', 'theme-header');
	remove_submenu_page('theme-config', 'theme-footer');
	remove_submenu_page('theme-config', 'theme-social');
	remove_submenu_page('theme-config', 'theme-scripts');

	// Re-add submenus in the desired order
	add_submenu_page('theme-config', 'Theme Header Settings', 'Header', 'manage_options', 'theme-header', '');
	add_submenu_page('theme-config', 'Theme Footer Settings', 'Footer', 'manage_options', 'theme-footer', '');
	add_submenu_page('theme-config', 'Theme Social Settings', 'Social', 'manage_options', 'theme-social', '');
	add_submenu_page('theme-config', 'Theme Scripts Settings', 'Scripts', 'manage_options', 'theme-scripts', '');
}, 999);


/*
// Disable all update notifications
add_filter( 'pre_site_transient_update_core', '__return_null' );
add_filter( 'pre_site_transient_update_plugins', '__return_null' );
add_filter( 'pre_site_transient_update_themes', '__return_null' );
*/

// Remove the red update notification bubble (the red dot)
// Using admin css to hide the red dot
// Add custom admin css
function custom_admin_css() {
    wp_enqueue_style('custom-admin-style', get_template_directory_uri() . '/css/admin-style.css');
}
add_action('admin_enqueue_scripts', 'custom_admin_css');

//--------------------------------------------------------
// Function to remove specific submenu items
// under "Appearance" in the WordPress admin
//--------------------------------------------------------
function cd_customize_appearance_menu() {
	// Remove the "Themes" link from the Appearance menu
	remove_submenu_page('themes.php', 'themes.php');

	// Remove the "Customize" link, targeting any URL that includes 'customize.php'
	global $submenu;
	if (isset($submenu['themes.php'])) {
		foreach ($submenu['themes.php'] as $index => $menu_item) {
			if ($menu_item[2] === 'customize.php' || strpos($menu_item[2], 'customize.php') !== false) {
				unset($submenu['themes.php'][$index]);
			}
		}
	}

	// Optionally remove the "Menus" link (commented out for now)
	// remove_submenu_page('themes.php', 'nav-menus.php');

	// Remove the "Widgets" link from the Appearance menu
	remove_submenu_page('themes.php', 'widgets.php');

	// Remove the "Header" link from the Appearance menu
	remove_submenu_page('themes.php', 'custom-header');

	// Optionally remove the "Theme File Editor" link (commented out for now)
	// remove_submenu_page('themes.php', 'theme-editor.php');

	// Remove the "Patterns" link from the Appearance menu
	remove_submenu_page('themes.php', 'site-editor.php?path=/patterns');
}

// Hook the function to the admin menu action with high priority (999)
add_action('admin_menu', 'cd_customize_appearance_menu', 999);


/**
 * Default Open Graph meta tags for title, description, and image.
 *
 * These functions hook into Yoast SEO's Open Graph filters to override default meta tags
 * with values from custom fields set in WordPress options. If a default value is provided 
 * in the custom fields, it replaces the corresponding meta tag generated by Yoast SEO. 
 * If no default value is set, the original value from Yoast SEO is used.
 *
 * - `cd_default_opengraph_title`: Overrides the Open Graph title.
 * - `cd_default_opengraph_description`: Overrides the Open Graph description.
 * - `cd_default_opengraph_image`: Overrides the Open Graph image URL.
 *
 * This approach ensures that the default Open Graph meta tags are used when configured,
 * allowing for flexible and dynamic content management.
 */

// Default Open Graph title
// use for override homepage title
add_filter('wpseo_opengraph_title', 'cd_default_opengraph_title');
function cd_default_opengraph_title($title) {
	if (is_front_page() || is_home()) {
		$default_og_title = get_field('default_og_title', 'option');
		return !empty($default_og_title) ? $default_og_title : $title;
	}
	return $title;
}

// Default Open Graph description
// set as default og:description when yoast is empty
add_filter('wpseo_opengraph_desc', 'cd_default_opengraph_description', 20, 1);
function cd_default_opengraph_description($description) {
	// if (is_front_page() || is_home()) {
	// 	$default_og_description = get_field('default_og_description', 'option');
	// 	return !empty($default_og_description) ? $default_og_description : $description;
	// }
	// return $description;

	if (empty($description)) {
		$default_og_description = get_field('default_og_description', 'option');
		if (!empty($default_og_description)) {
			$description = $default_og_description;
		}
	}

	return $description;

}

// Default Open Graph image
// // ClueEdit: this filter is only called when og:image is not empty. so it useless for creating a fallback image
// add_filter('wpseo_opengraph_image', 'cd_default_opengraph_image');
// function cd_default_opengraph_image($image) {
// 	if (is_front_page() || is_home()) {
// 		$default_og_image_id = get_field('default_og_image', 'option');
// 		if ($default_og_image_id) {
// 			$og_image = wp_get_attachment_image_src($default_og_image_id, 'full');
// 			return $og_image[0];
// 		}
// 	}
// 	return $image;
// }
// use this instead
// add_action( 'wpseo_add_opengraph_images', 'cd_add_opengraph_images' );
// function cd_add_opengraph_images( $object ) {
// // var_dump($object['images']);
//  $images = $object->get_images(); 
//  var_dump($images);
//  if (empty($images)) {
// 	$default_og_image_id = get_field('default_og_image', 'option');
// 	if ($default_og_image_id) {
// 		$og_image = wp_get_attachment_image_src($default_og_image_id, 'full');
// 		$object->add_image( $og_image[0] );
// 	} 
//  }
// }
// use this instead
add_filter('wpseo_opengraph', 'cd_add_opengraph_image');
function cd_add_opengraph_image() {
    // Check if an Open Graph image is already set
    global $post;
	if (isset($post) && $post) {
		$og_image = get_post_meta($post->ID, '_yoast_wpseo_opengraph-image', true);

		if (empty($og_image)) {
			// No Open Graph image is set, use the default image
			$default_og_image_id = get_field('default_og_image', 'option');
			if ($default_og_image_id) {
				$og_image_src = wp_get_attachment_image_src($default_og_image_id, 'full');
				if ($og_image_src) {
					echo '<meta property="og:image" content="' . esc_url($og_image_src[0]) . '" />';
				}
			}
		}
	}
}

/**
 * Outputs default Open Graph meta tags for the site if they are not already set by Yoast SEO.
 *
 * This function retrieves default Open Graph information from custom fields set in the WordPress options.
 * If these fields are set and Yoast SEO is not managing them, the function generates and outputs the appropriate meta tags for Open Graph.
 *
 * Open Graph tags included:
 * - `og:image`: The URL of the image to be used as the Open Graph image.
 * - `og:title`: The title to be used as the Open Graph title.
 * - `og:description`: The description to be used as the Open Graph description.
 *
 * This function is hooked into the `wp_head` action to ensure that these meta tags are included in the HTML `<head>` section of the page.
 *
 * Note: This function may create duplicate Open Graph tags if Yoast SEO is also setting them.
 * It is advisable to ensure that Yoast SEO and this function are not both setting the same Open Graph tags to avoid duplication.
 */
function cd_default_open_graph_info() {
	// Global default Open Graph settings
	$default_og_image_id = get_field('default_og_image', 'option');
	$default_og_title = get_field('default_og_title', 'option');
	$default_og_description = get_field('default_og_description', 'option');

	// Page/Post-specific Open Graph info
	global $post;
	$page_og_title = get_the_title($post->ID);
	$page_og_description = get_the_excerpt($post->ID);
	$page_og_image_id = get_post_thumbnail_id($post->ID);

	// Determine Open Graph values, prioritizing page-specific values
	$og_title = $page_og_title ? $page_og_title : $default_og_title;
	$og_description = $page_og_description ? $page_og_description : $default_og_description;

	if ($page_og_image_id) {
		$og_image = wp_get_attachment_image_src($page_og_image_id, 'full');
	} elseif ($default_og_image_id) {
		$og_image = wp_get_attachment_image_src($default_og_image_id, 'full');
	} else {
		$og_image = null;
	}

	// Get the current page URL
	$current_url = is_front_page() ? home_url() : get_permalink();

	// Output Open Graph meta tags
	if ($og_title) {
		echo '<meta property="og:title" content="' . esc_attr($og_title) . '" />';
	}

	if ($og_description) {
		echo '<meta property="og:description" content="' . esc_attr($og_description) . '" />';
	}

	if ($og_image && !empty($og_image[0])) {
		echo '<meta property="og:image" content="' . esc_url($og_image[0]) . '" />';
	}

	echo '<meta property="og:url" content="' . esc_url($current_url) . '" />';
}

// Hook the function into the 'wp_head' action with a priority of 36
//add_action('wp_head', 'cd_default_open_graph_info', 36);

// Hook the function into the 'wp_head' action with a priority of 1, so it's on top
//add_action('wp_head', 'cd_default_open_graph_info', 1);



/**
 * Filter the document title specifically for the homepage using ACF.
 *
 * This function attempts to modify the document title for the homepage by retrieving a custom title from ACF (Advanced Custom Fields).
 * However, this filter may not work as intended because Yoast SEO can override the title set by this filter.
 *
 * @param string $title The current document title.
 * @return string Modified document title. If a custom title is set in ACF, it is returned; otherwise, the original title is retained.
 */
function cd_custom_homepage_title($title) {
	if (is_front_page() || is_home()) {
		$site_title = get_field('site_title', 'option'); // Fetch the site title from ACF options
		return !empty($site_title) ? $site_title : $title; // Use the ACF title or fallback to the default
	}
	return $title;
}
//add_filter('pre_get_document_title', 'cd_custom_homepage_title');


/**
 * Customize the Yoast SEO title specifically for the homepage using ACF.
 *
 * This function modifies the title output by Yoast SEO for the homepage by retrieving a custom title from ACF (Advanced Custom Fields).
 * If a custom title is set in ACF, it will replace the default Yoast SEO title for the homepage.
 *
 * @param string $title The current title as set by Yoast SEO.
 * @return string The modified title. Returns the custom ACF title if available; otherwise, the original Yoast SEO title is returned.
 */
/*
function cd_custom_wpseo_title($title) {
	if (is_front_page() || is_home()) {
		$site_title = get_field('site_title', 'option'); // Fetch the site title from ACF options
		return !empty($site_title) ? $site_title : $title; // Use the ACF title or fallback to the default
	}
	return $title;
}
add_filter('wpseo_title', 'cd_custom_wpseo_title');
*/

/**
 * Override the favicon in both the front end and admin area.
 *
 * This function sets a custom favicon for the WordPress site by retrieving the favicon ID from the Theme Config Settings using ACF (Advanced Custom Fields). 
 * It outputs the necessary HTML tags to set the favicon for standard, high-resolution, and Apple touch icons.
 * 
 * The favicon ID is retrieved from the 'site_favicon' field in the ACF options page. If a valid favicon URL is found, it will be used to set the favicon 
 * for different device resolutions.
 * 
 * @return void Outputs HTML link tags for the favicon if a valid URL is found.
 */
function cd_custom_admin_favicon() {
	// Retrieve the favicon ID from the Theme Config Settings using ACF
	$favicon_id = get_field('site_favicon', 'option');
	
	// Check if a custom favicon is set
	if ($favicon_id) {
		// Get the URL of the favicon image in 'full' size
		$favicon_url = wp_get_attachment_image_url($favicon_id, 'full');
		
		// If a valid favicon URL is found, output the relevant HTML tags
		if ($favicon_url) {
			// Set the favicon for standard, high-resolution, and Apple touch icons
			echo '<link rel="icon" href="' . esc_url($favicon_url) . '" sizes="32x32" />';
			echo '<link rel="icon" href="' . esc_url($favicon_url) . '" sizes="192x192" />';
			echo '<link rel="apple-touch-icon" href="' . esc_url($favicon_url) . '" />';
		}
	}
}
// Apply the custom favicon to the WordPress admin area and login page
add_action('admin_head', 'cd_custom_admin_favicon');
add_action('login_head', 'cd_custom_admin_favicon');


/**
 * Modify the Gravity Forms submit button from an <input> to a <button> element.
 * This function preserves any custom button text defined in the form settings.
 * 
 * - Retrieves the submit button text using the Gravity Forms form object.
 * - Changes the default <input> to a <button> element for better flexibility and customization.
 * - Wraps the submit button text inside a <span class="link_text"> for styling purposes.
 * - Maintains the form-specific ID for the button.
 * 
 * @param string $button The original submit button HTML.
 * @param array $form The Gravity Forms form object, which contains form-specific data like the form ID and button text.
 * @return string Modified submit button HTML with a <button> element and wrapped text.
 */
// add_filter('gform_submit_button', 'cd_custom_gf_submit_button', 10, 2);
function cd_custom_gf_submit_button($button, $form) {
    // Get the submit button text from the form settings
    $submit_text = esc_html($form['button']['text']);

    // Create custom button HTML with the text wrapped in a <span class="link_text">
    return '<button class="gform_button button" type="submit" id="gform_submit_button_' . esc_attr($form['id']) . '"><span class="link-text">' . $submit_text . '</span></button>';
}


/**
 * Load more posts
 */
function cd_load_more_posts() {
	$paged = isset($_POST['page']) ? intval($_POST['page']) + 1 : 1;
	$category = isset($_POST['category']) ? $_POST['category'] : '';

	$args = array(
			'post_type' => 'post',
			'posts_per_page' => 12,
			'paged' => $paged,
			'post_status' => 'publish',
			'post__not_in' => get_option('sticky_posts'), // assume there's no sticky post in page 2 and so on
		);

	if ($category) {
			$args['category_name'] = $category;
	}

	$posts = new WP_Query($args);

	if ($posts->have_posts()) :
			while ($posts->have_posts()) : $posts->the_post();
					echo '<div class="col-md-6 col-lg-4">';
					get_template_part('loop-templates/content', get_post_format());
					echo '</div>';
			endwhile;
	endif;

	wp_die();
}
add_action('wp_ajax_load_more', 'cd_load_more_posts');
add_action('wp_ajax_nopriv_load_more', 'cd_load_more_posts');


/**
 * remove the Gravity form Tab index to solve issue with Tabbed to the footer form
 */
add_filter( 'gform_tabindex', '__return_false' ); 


/**
 * FAQ Schema
 * insert the FAQ schema in WP_footer
 */
global $all_faqs;	// global variable to store the FAQs
$all_faqs = [];		// Reset the global variable

add_action('wp_footer', function() {
	global $all_faqs;	// global variable for the FAQs

	if (!empty($all_faqs)) {
		$faqSchema = [
			"@context" => "https://schema.org",
			"@type" => "FAQPage",
			"mainEntity" => array_map(function($faq) {
				return [
					"@type" => "Question",
					"name" => $faq['question'],
					"acceptedAnswer" => [
						"@type" => "Answer",
						"text" => $faq['answer']
					]
				];
			}, $all_faqs)
		];

		echo '<script type="application/ld+json">' . json_encode($faqSchema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) . '</script>';
	}
});


/**
 * User's Custom Script 
 * location: header, body and footer
 */
function cd_get_allowed_script_tags() {
	return array(
		'noscript' => array(), // Allow <noscript> tag
		'iframe' => array( // Allow <iframe> tag and its attributes
			'src' => array(),
			'height' => array(),
			'width' => array(),
			'style' => array(),
		),
		'script' => array( // Allow <script> tag and its attributes
			'src' => array(),
			'type' => array(),
			'async' => array(),
			'defer' => array(),
			'data-key' => array(),
		),
	);
}

function cd_custom_header_script() {
	$header_script = get_field('script_header', 'option'); // Get ACF field
	if ($header_script) {
		echo wp_kses($header_script, cd_get_allowed_script_tags());
	}
}
add_action('wp_head', 'cd_custom_header_script');

function cd_custom_body_open_script() {
	$body_script = get_field('script_body', 'option'); // Get ACF field
	if ($body_script) {
		echo wp_kses($body_script, cd_get_allowed_script_tags());
	}
}
add_action('wp_body_open', 'cd_custom_body_open_script');

function cd_custom_footer_script() {
	$footer_script = get_field('script_footer', 'option'); // Get ACF field
	if ($footer_script) {
		echo $footer_script; // dangerous, but we trust the user to input valid script
	}
}
add_action('wp_footer', 'cd_custom_footer_script');

// ClueEdit - yoast meta description
add_filter('wpseo_metadesc', 'cd_wpseo_metadesc', 10, 1);

function cd_wpseo_metadesc($metadesc) {
		// for blogpost, if meta description empty, use excerpt as default
    if (is_singular('post') && empty($metadesc)) {
        global $post;
        $excerpt = get_the_excerpt($post);
        if (!empty($excerpt)) {
            return wp_strip_all_tags($excerpt);
        }
    }
    return $metadesc;
}